services:
  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: demopostgres
      POSTGRES_USER: contributte
      POSTGRES_PASSWORD: contributte
    ports:
      - 5432:5432
    volumes:
      - ./.data/postgres/data/:/var/lib/postgresql/data

  mariadb:
    image: mariadb:10.10
    restart: always
    environment:
      MARIADB_DATABASE: demomariadb
      MARIADB_USER: contributte
      MARIADB_PASSWORD: contributte
      MARIADB_ROOT_PASSWORD: contributte
    ports:
      - 3306:3306
    volumes:
      - ./.data/mariadb/data/:/var/lib/mysql
